using System;
using System.Collections.Generic;
using System.Text;
using System.Numerics;

namespace GameServer
{
    class MapPrefabs
    {
        private static Platform[,] prefab0 =
        {
            {
                null,
                null,
                new Platform(new Vector2(0.4f, 0f), new Vector2(1.0f, 1.0f), Platform.PlatformType.SimplePlatform),
                null,
                null,
                null,
                null,
                new Platform(new Vector2(-1.0f, -1f), new Vector2(-0.4f, 1f), Platform.PlatformType.SimplePlatform),
                null,
                null,
                null,
                new Platform(new Vector2(0.5f, 0f), new Vector2(1.0f, 0.6f), Platform.PlatformType.SimplePlatform),
                new Platform(new Vector2(-1.0f, 0f), new Vector2(1.0f, 0.6f), Platform.PlatformType.SimplePlatform),
                new Platform(new Vector2(-1.0f, 0f), new Vector2(1.0f, 0.6f), Platform.PlatformType.SimplePlatform),
                new Platform(new Vector2(-1.0f, 0f), new Vector2(1.0f, 0.6f), Platform.PlatformType.SimplePlatform),
                new Platform(new Vector2(-1.0f, 0f), new Vector2(0f, 0.6f), Platform.PlatformType.SimplePlatform),
                null,
                null
            },
            {
                null,
                null,
                new Platform(new Vector2(0.4f, -1f), new Vector2(1f, 0.6f), Platform.PlatformType.SimplePlatform),
                new Platform(new Vector2(-1f, 0f), new Vector2(1f, 0.6f), Platform.PlatformType.SimplePlatform),
                new Platform(new Vector2(-1f, 0f), new Vector2(1f, 0.6f), Platform.PlatformType.SimplePlatform),
                new Platform(new Vector2(-1f, 0f), new Vector2(1f, 0.6f), Platform.PlatformType.SimplePlatform),
                new Platform(new Vector2(-1f, 0f), new Vector2(1f, 0.6f), Platform.PlatformType.SimplePlatform),
                new Platform(new Vector2(-1.0f, -1f), new Vector2(-0.4f, 0.6f), Platform.PlatformType.SimplePlatform),
                null,
                null,
                null,
                null,
                null,
                new Platform(new Vector2(0.4f, 0.8f), new Vector2(1f, 1f), Platform.PlatformType.SimplePlatform),
                null,
                null,
                null,
                null
            },
            {
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                new Platform(new Vector2(-1f, 0.1f), new Vector2(-0.4f, 1f), Platform.PlatformType.SimplePlatform),
                null,
                new Platform(new Vector2(0.4f, -1f), new Vector2(1f, 0.6f), Platform.PlatformType.SimplePlatform),
                new Platform(new Vector2(-1f, 0f), new Vector2(1f, 0.6f), Platform.PlatformType.SimplePlatform),
                new Platform(new Vector2(-1f, 0f), new Vector2(1f, 0.6f), Platform.PlatformType.SimplePlatform),
                new Platform(new Vector2(-1f, 0f), new Vector2(1f, 0.6f), Platform.PlatformType.SimplePlatform),
                new Platform(new Vector2(-1f, 0f), new Vector2(0.5f, 0.6f), Platform.PlatformType.SimplePlatform)
            },
            {
                null,
                null,
                null,
                null,
                null,
                null,
                new Platform(new Vector2(-0.5f, 0f), new Vector2(1f, 0.6f), Platform.PlatformType.SimplePlatform),
                new Platform(new Vector2(-1f, 0f), new Vector2(1f, 0.6f), Platform.PlatformType.SimplePlatform),
                new Platform(new Vector2(-1f, 0f), new Vector2(1f, 0.6f), Platform.PlatformType.SimplePlatform),
                new Platform(new Vector2(-1f, 0f), new Vector2(1f, 0.6f), Platform.PlatformType.SimplePlatform),
                new Platform(new Vector2(-1f, 0f), new Vector2(1f, 0.6f), Platform.PlatformType.SimplePlatform),
                new Platform(new Vector2(-1f, -1f), new Vector2(-0.4f, 0.6f), Platform.PlatformType.SimplePlatform),
                null,
                null,
                null,
                null,
                null,
                null
            },
            {
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null
            },
            {
                null,
                null,
                null,
                null,
                new Platform(new Vector2(-1f, -0.6f), new Vector2(-0.4f, 1f), Platform.PlatformType.SimplePlatform),
                null,
                null,
                null,
                null,
                null,
                new Platform(new Vector2(-1f, 0f), new Vector2(-0.4f, 1f), Platform.PlatformType.SimplePlatform),
                null,
                null,
                new Platform(new Vector2(-1f, 0.7f), new Vector2(1f, 1f), Platform.PlatformType.TransparentPlatform),
                new Platform(new Vector2(-1f, 0.7f), new Vector2(1f, 1f), Platform.PlatformType.TransparentPlatform),
                new Platform(new Vector2(-1f, 0.7f), new Vector2(1f, 1f), Platform.PlatformType.TransparentPlatform),
                null,
                null
            },
            {
                null,
                new Platform(new Vector2(-1f, -0.4f), new Vector2(1f, 0.2f), Platform.PlatformType.SimplePlatform),
                new Platform(new Vector2(-1f, -0.4f), new Vector2(1f, 0.2f), Platform.PlatformType.SimplePlatform),
                new Platform(new Vector2(-1f, -0.4f), new Vector2(1f, 0.2f), Platform.PlatformType.SimplePlatform),
                new Platform(new Vector2(-1f, -1f), new Vector2(-0.4f, 0.2f), Platform.PlatformType.SimplePlatform),
                null,
                new Platform(new Vector2(-0.4f, -0.4f), new Vector2(1f, 0.2f), Platform.PlatformType.SimplePlatform),
                new Platform(new Vector2(-1f, -0.4f), new Vector2(1f, 0.2f), Platform.PlatformType.SimplePlatform),
                new Platform(new Vector2(-1f, -0.4f), new Vector2(1f, 0.2f), Platform.PlatformType.SimplePlatform),
                new Platform(new Vector2(-1f, -0.4f), new Vector2(1f, 0.2f), Platform.PlatformType.SimplePlatform),
                new Platform(new Vector2(-1f, -1f), new Vector2(-0.4f, 0.2f), Platform.PlatformType.SimplePlatform),
                null,
                null,
                null,
                null,
                null,
                null,
                null
            },
            {
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null
            },
            {
                null,
                null,
                null,
                new Platform(new Vector2(0.6f, -0.3f), new Vector2(1f, 0f), Platform.PlatformType.TransparentPlatform),
                new Platform(new Vector2(-1f, -0.3f), new Vector2(1f, 0f), Platform.PlatformType.TransparentPlatform),
                new Platform(new Vector2(-1f, -0.3f), new Vector2(1f, 0f), Platform.PlatformType.TransparentPlatform),
                new Platform(new Vector2(-1f, -0.3f), new Vector2(1f, 0f), Platform.PlatformType.TransparentPlatform),
                new Platform(new Vector2(-1f, -0.3f), new Vector2(-0.6f, 0f), Platform.PlatformType.TransparentPlatform),
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null
            },
            {
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null
            }
        };

        public static SuperConstruct[] prefabs =
        {
            new SuperConstruct(prefab0)
        };
    }
}
